version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "lockfile-only"
    labels:
      - "dependencies"
      - "automerge-minor"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "lockfile-only"
    labels:
      - "dependencies"
      - "automerge-minor"
