name: Auto Merge

on:
  pull_request:
    types:
      - labeled
  check_suite:
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "dependencies,automerge-minor"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "chore: merge PR"
          MERGE_FORKS: "false"
          UPDATE_BRANCH: "true"
